version: '3.8'

services:
  activity-api:
    build:
      context: .
      dockerfile: SaudeBemEstaApp.Activity.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: adroaldojr/activityapi:v2
    ports:
      - "8001:80"

  appointment-api:
    build:
      context: .
      dockerfile: SaudeBemEstaApp.Appointment.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: adroaldojr/appointmentapi:v2
    ports:
      - "8002:80"

  notifications-api:
    build:
      context: .
      dockerfile: SaudeBemEstaApp.Notifications.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: adroaldojr/notificationsapi:v2
    ports:
      - "8003:80"

  patient-api:
    build:
      context: .
      dockerfile: SaudeBemEstaApp.Patient.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: adroaldojr/patientapi:v2
    ports:
      - "8004:80"

  prescription-api:
    build:
      context: .
      dockerfile: SaudeBemEstaApp.Prescription.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: adroaldojr/prescriptionapi:v2
    ports:
      - "8005:80"

  domain:
    build:
      context: .
      dockerfile: SaudeBemEstaApp.Domain/Dockerfile

  infrastructure:
    build:
      context: .
      dockerfile: SaudeBemEstaApp.Infrastructure/Dockerfile
