version: '3.8'

services:
  activity-api:
    build:
      context: ./SaudeBemEstaApp.Activity.API
      args:
        BUILD_CONFIGURATION: Release
    image: adroaldojr/activityapi:v1
    ports:
      - "8001:80"

  appointment-api:
    build:
      context: ./SaudeBemEstaApp/SaudeBemEstaApp.Appointments.API
      args:
        BUILD_CONFIGURATION: Release
    image: adroaldojr/appointmentapi:v1
    ports:
      - "8002:80"

  notifications-api:
    build:
      context: ./SaudeBemEstaApp/SaudeBemEstaApp.Notifications.API
      args:
        BUILD_CONFIGURATION: Release
    image: adroaldojr/notificationsapi:v1
    ports:
      - "8003:80"

  patient-api:
    build:
      context: ./SaudeBemEstaApp/SaudeBemEstaApp.Patients
      args:
        BUILD_CONFIGURATION: Release
    image: adroaldojr/patientapi:v1
    ports:
      - "8004:80"

  prescription-api:
    build:
      context: ./SaudeBemEstaApp/SaudeBemEstaApp.Prescriptions.API
      args:
        BUILD_CONFIGURATION: Release
    image: adroaldojr/prescriptionapi:v1
    ports:
      - "8005:80"

  domain:
    build:
      context: ./SaudeBemEstaApp.Domain

  infrastructure:
    build:
      context: ./SaudeBemEstaApp.Infrastructure
