name: Build and Push ASP.NET Core Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v2

      - name: Configurar .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x' # Especifique a versão do .NET que você está usando

      - name: Restaurar dependências
        run: dotnet restore SaudeBemEstaApp.sln

      - name: Compilar
        run: dotnet build SaudeBemEstaApp.sln --configuration Release --no-restore

      - name: Publicar
        run: dotnet publish SaudeBemEstaApp.sln --configuration Release --no-restore -o ./publish

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compilar e enviar a imagem Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: adroaldojr/saudebemestarapp:v1

      - name: Limpar
        run: |
          docker system prune -f
