name: Build and Push ASP.NET Core Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v2

      - name: Configurar .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x' # Especifique a versão do .NET que você está usando

      - name: Restaurar dependências
        run: |
          cd SaudeBemEstaApp
          dotnet restore ./SaudeBemEstaApp.Activity.API.csproj
          dotnet restore ./SaudeBemEstaApp.Appointment.API.csproj
          dotnet restore ./SaudeBemEstaApp.Domain.csproj
          dotnet restore ./SaudeBemEstaApp.Infrastructure.csproj
          dotnet restore ./SaudeBemEstaApp.Messaging.csproj
          dotnet restore ./SaudeBemEstaApp.Notifications.API.csproj
          dotnet restore ./SaudeBemEstaApp.Patient.csproj
          dotnet restore ./SaudeBemEstaApp.Prescription.API.csproj

      - name: Compilar
        run: |
          cd SaudeBemEstaApp
          dotnet build ./SaudeBemEstaApp.Activity.API.csproj --configuration Release --no-restore
          dotnet build ./SaudeBemEstaApp.Appointment.API.csproj --configuration Release --no-restore
          dotnet build ./SaudeBemEstaApp.Domain.csproj --configuration Release --no-restore
          dotnet build ./SaudeBemEstaApp.Infrastructure.csproj --configuration Release --no-restore
          dotnet build ./SaudeBemEstaApp.Messaging.csproj --configuration Release --no-restore
          dotnet build ./SaudeBemEstaApp.Notifications.API.csproj --configuration Release --no-restore
          dotnet build ./SaudeBemEstaApp.Patient.csproj --configuration Release --no-restore
          dotnet build ./SaudeBemEstaApp.Prescription.API.csproj --configuration Release --no-restore

      - name: Publicar
        run: |
          cd SaudeBemEstaApp
          dotnet publish .SaudeBemEstaApp.Activity.API.csproj --configuration Release --no-restore -o ./publish/SaudeBemEstaApp.Activity.API
          dotnet publish ./SaudeBemEstaApp.Appointment.API.csproj --configuration Release --no-restore -o ./publish/SaudeBemEstaApp.Appointment.API
          dotnet publish ./SaudeBemEstaApp.Domain.csproj --configuration Release --no-restore -o ./publish/SaudeBemEstaApp.Domain
          dotnet publish ./SaudeBemEstaApp.Infrastructure.csproj --configuration Release --no-restore -o ./publish/SaudeBemEstaApp.Infrastructure
          dotnet publish ./SaudeBemEstaApp.Messaging.csproj --configuration Release --no-restore -o ./publish/SaudeBemEstaApp.Messaging
          dotnet publish ./SaudeBemEstaApp.Notifications.API.csproj --configuration Release --no-restore -o ./publish/SaudeBemEstaApp.Notifications.API
          dotnet publish . --configuration Release --no-restore -o ./publish/SaudeBemEstaApp.Patient
          dotnet publish .SaudeBemEstaApp.Prescription.API.csproj --configuration Release --no-restore -o ./publish/SaudeBemEstaApp.Prescription.API

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compilar e enviar a imagem Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: adroaldojr/saudebemestarapp:v1

      - name: Limpar
        run: |
          docker system prune -f
