name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # ou qualquer branch que você use para deployment

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push activity-api
      uses: docker/build-push-action@v2
      with:
        context: SaudeBemEstaApp.Activities.API
        file: ./SaudeBemEstaApp.Activity.API/Dockerfile
        push: true
        tags: adroaldojr/activityapi:v1

    - name: Build and push appointment-api
      uses: docker/build-push-action@v2
      with:
        context: ./SaudeBemEstaApp.Appointments.API
        file: ./SaudeBemEstaApp.Appointment.API/Dockerfile
        push: true
        tags: adroaldojr/appointmentapi:v1

    - name: Build and push notifications-api
      uses: docker/build-push-action@v2
      with:
        context: ./SaudeBemEstaApp.Notifications.API
        file: ./SaudeBemEstaApp.Notifications.API/Dockerfile
        push: true
        tags: adroaldojr/notificationsapi:v1

    - name: Build and push patient-api
      uses: docker/build-push-action@v2
      with:
        context: ./SaudeBemEstaApp.Patients.API
        file: ./SaudeBemEstaApp.Patient/Dockerfile
        push: true
        tags: adroaldojr/patientapi:v1

    - name: Build and push prescription-api
      uses: docker/build-push-action@v2
      with:
        context: ./SaudeBemEstaApp.Prescriptions.API
        file: ./SaudeBemEstaApp.Prescription.API/Dockerfile
        push: true
        tags: adroaldojr/prescriptionapi:v1
