name: Build and Push Docker images

on:
  push:
    branches:
      - main
    paths:
      - 'SaudeBemEstaApp.*/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # Executa todos os dias às 02:00 UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Activity API image
      uses: docker/build-push-action@v2
      with:
        context: ./SaudeBemEstaApp.Activity.API
        file: ./SaudeBemEstaApp.Activity.API/Dockerfile
        push: true
        tags: adroaldojr/activityapi:v1
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache

    - name: Build and push Appointment API image
      uses: docker/build-push-action@v2
      with:
        context: ./SaudeBemEstaApp.Appointment.API
        file: ./SaudeBemEstaApp.Appointment.API/Dockerfile
        push: true
        tags: adroaldojr/appointmentapi:v1
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache

    - name: Build and push Messaging API image
      uses: docker/build-push-action@v2
      with:
        context: ./SaudeBemEstaApp.Messaging
        file: ./SaudeBemEstaApp.Messaging/Dockerfile
        push: true
        tags: adroaldojr/messagingapi:v1
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache

    - name: Build and push Notifications API image
      uses: docker/build-push-action@v2
      with:
        context: ./SaudeBemEstaApp.Notifications.API
        file: ./SaudeBemEstaApp.Notifications.API/Dockerfile
        push: true
        tags: adroaldojr/notificationsapi:v1
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache

    - name: Build and push Prescription API image
      uses: docker/build-push-action@v2
      with:
        context: ./SaudeBemEstaApp.Prescription.API
        file: ./SaudeBemEstaApp.Prescription.API/Dockerfile
        push: true
        tags: adroaldojr/prescriptionapi:v1
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
